<?php

/**
 * @file
 * Module entry point.
 *
 * This file calls the hook_form_alter
 * to manipulate the form preview button.
 */

/**
 * Alters the forms to hide the preview button if needed.
 *
 * @inheritdoc
 */
function hide_preview_form_alter(&$form, $form_state, $form_id) {
  $config = Drupal::config('hide_preview.settings');
  $formNames = $config->get('hide_preview.form_names');

  // Check if it is a regexp or a simple string.
  foreach ($formNames as $name) {
    if (@preg_match($name, $form_id, $matches) !== FALSE) {
      if (count($matches)) {
        $form['actions']['preview']['#access'] = FALSE;
      }
    }
    elseif (strpos($form_id, 'contact_message_') !== FALSE) {
      $form['actions']['preview']['#access'] = FALSE;
    }
  }
}
